wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.23
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.8
      5: 0.10.23
      8:
      - 5
algo:
  desc: null
  value: ppo
alpha:
  desc: null
  value: 0.99
clip_param:
  desc: null
  value: 0.2
config:
  desc: null
  value: default
cuda:
  desc: null
  value: true
cuda_deterministic:
  desc: null
  value: false
entropy_coef:
  desc: null
  value: 0.0
env_name:
  desc: null
  value: aliengo
env_params:
  desc: null
  value:
    action_repeat: 4
    apply_perturb: false
    avg_time_per_perturb: 5.0
    env_mode: pmtg
    fixed: false
    fixed_orientation:
    - 0
    - 0
    - 0
    fixed_position:
    - 0
    - 0
    - 1.0
    flat_ground: true
    gait_type: trot
    kd: 1.0
    kp: 1.0
    max_torque: 44.4
    realTime: false
    render: false
    timeout: 60.0
    vis: false
eps:
  desc: null
  value: 1.0e-05
eval_interval:
  desc: null
  value: null
gae_lambda:
  desc: null
  value: 0.95
gail:
  desc: null
  value: false
gail_batch_size:
  desc: null
  value: 128
gail_epoch:
  desc: null
  value: 5
gail_experts_dir:
  desc: null
  value: ./gail_experts
gait_type:
  desc: null
  value: trot
gamma:
  desc: null
  value: 0.99
gpu_idx:
  desc: null
  value: 0
log_dir:
  desc: null
  value: /tmp/gym/
log_interval:
  desc: null
  value: 1
lr:
  desc: null
  value: 3.0e-05
max_grad_norm:
  desc: null
  value: 0.5
num_env_steps:
  desc: null
  value: 100000000
num_mini_batch:
  desc: null
  value: 32
num_processes:
  desc: null
  value: 1
num_steps:
  desc: null
  value: 600
num_torch_threads:
  desc: null
  value: null
ppo_epoch:
  desc: null
  value: 10
recurrent_policy:
  desc: null
  value: false
save_dir:
  desc: null
  value: ./trained_models/
save_interval:
  desc: null
  value: 100
seed:
  desc: null
  value: 1
use_gae:
  desc: null
  value: true
use_linear_lr_decay:
  desc: null
  value: false
use_proper_time_limits:
  desc: null
  value: true
value_loss_coef:
  desc: null
  value: 0.5
wandb_log_interval:
  desc: null
  value: 100
wandb_project:
  desc: null
  value: default
