# Logging and Saving
wandb_project: TEST_PENDULUM
log_interval: 1
save_interval: 1
wandb_log_interval: 1

# RL parameters
algo: ppo
gpu_idx: 0
hidden_size: 32
lr: 3.0e-4
gamma: 0.99
use_gae: True
gae_lambda: 0.95
entropy_coef: 0.00
value_loss_coef: 0.5
max_grad_norm: 0.5
seed: 1
cuda_deterministic: False
num_processes: 16
num_steps: 125
ppo_epoch: 10
num_mini_batch: 32
clip_param: 0.2
eval_interval: null
num_env_steps: 200_000
env_name: Pendulum-v0
log_dir: /tmp/gym/
cuda: False
use_proper_time_limits: True
recurrent_policy: False
use_linear_lr_decay: True
num_torch_threads: null